
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Hemananda 123",
    "email": "test222@gmail.com",
    "address": "street no 6",
    "dateOfBirth":"2003-06-04",
    "registeredDate": "2025-10-04"
}